/********* Sample code generated by the curl command line tool **********
 * All curl_easy_setopt() options are documented at:
 * http://curl.haxx.se/libcurl/c/curl_easy_setopt.html
 ************************************************************************/
#ifndef CURL_HTTP_H
#define CURL_HTTP_H

#include <string>
#include <curl/curl.h>
#include "jtypes.h"

// A wrapper class for http request based on curl
namespace curl
{
  class HttpRequest
  {
  public:
    HttpRequest();
    ~HttpRequest();
    void setContentType(const char* mimeType);
    JObject* getJSON(const char* url);
    static JObject* getJSONFromFile(const char* filename);
  private:
    std::string data;
    CURLcode ret;
    curl_slist *slist;
    CURL *hnd;
  };
}
#endif
